version: '3'
services:
  mongodb:
    image: mongo
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.5", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_BASE_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - node-network

  backendapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_URL: "mongodb://mongodb:27017"
      MONGO_DB_BASE_DATABASE: ${MONGO_DB_BASE_DATABASE}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - node-network

networks:
  node-network:
    driver: bridge