version: '3'
services:
  mongodb:
    image: mongo
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.5", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_BASE_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  pythonapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_BASE_DATABASE: ${MONGO_DB_BASE_DATABASE}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
